CREATE DATABASE HomeWorkT2DB
ON
(
	NAME = 'HomeWorkT2DB',
	FILENAME = 'D:\MSSQL15.MSSQLSERVERDEV\MSSQL\MyData\HomeWorkT2DB.mdf',
	SIZE = 30 MB,
	MAXSIZE = 50 MB,
	FILEGROWTH = 5 MB
)
LOG ON
(
	NAME = 'HomeWorkT2DB_log',
	FILENAME = 'E:\HomeWorkT2DB_log.ldf',
	SIZE = 30 MB,
	MAXSIZE = 50 MB,
	FILEGROWTH = 5 MB
)
COLLATE Cyrillic_General_CI_AS

ALTER DATABASE HomeWorkT2DB MODIFY FILE(NAME = 'HomeWorkT2DB', MAXSIZE = 100 MB)


sp_helpdb HomeWorkT2DB

DROP DATABASE HomeWorkT2DB